mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]


urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.LoginView.as_view(), name='login'),
    url(r'^login/', views.login, name='loginauth'),
    url(r'^register/', views.register, name='register'),
    url(r'^index/', views.IndexView.as_view(), name='index'),
    url(r'^history/', views.HistoryView.as_view(), name='history'),
    url(r'^serverhistory/', views.serverhistory, name='serverhistory'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models.py
from __future__ import unicode_literals
from django.utils import timezone
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import User

import datetime


@python_2_unicode_compatible
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    user = models.ForeignKey(User, null=True)

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


@python_2_unicode_compatible
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Meta:
    ordering = ['choice_text']
    # Choice.objects.order_by('choice_text')

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Choice, Question, User
# from django.contrib.sessions import
from django.contrib.auth import authenticate  # , login


# from django.template.loader import render_to_string


class LoginView(generic.ListView):
    model = User
    template_name = 'polls/login.html'


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


class HistoryView(generic.ListView):
    model = Question
    template_name = 'polls/history.html'


def login(request):
    uname = request.POST['username']
    pwd = request.POST['password']
    user = authenticate(request, username=uname, password=pwd)
    if user is not None:
        return HttpResponse('ok')
    else:
        return HttpResponse('Wrong Credentials')


def register(request):
    uname = request.POST['username']
    pwd = request.POST['password']
    user = authenticate(request, username=uname, password=pwd)
    if user is None:
        ur = User(username=uname)
        ur.set_password(pwd)
        ur.save()
        return HttpResponse('registered')
    else:
        return HttpResponse('User exists!')


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):

        if request.is_ajax():
            return HttpResponse('You didn\'t select a choice.')
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

        tf = False
        squests = request.session.get("squests")
        if squests is None:
            squests = [{
                "Question": question.question_text,
                "Choice": selected_choice.choice_text,
                "Votes": 0
            }]
            request.session["squests"] = squests

        for i in squests:
            if i["Choice"] == selected_choice.choice_text:
                i["Votes"] += 1
                tf = True

        if tf is False:
            newquest = {"Question": question.question_text,
                        "Choice": selected_choice.choice_text,
                        "Votes": 1
                        }
            squests.append(newquest)
        request.session["squests"] = squests

        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def serverhistory(request):
    return render(request, 'polls/serverhistory.html')

polls/templates/polls/detail.html
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"/>
</head>
<html>
<head>
</head>
<body>
<div class="bg-img">
    <div style="width:100px;float:right;">
        <a href="/polls/" class="btn2" style="float:right;" id="logout_btn">Logout</a>
        <a href="/polls/index/" class="btn2" style="float:right;">Back</a>
        <a href="/polls/history/" id="history_button" class="btn2" style="float:right;">History</a>
        <a href="/polls/serverhistory/" id="shistory_button" class="btn2" style="float:right;">History(Server)</a>
    </div>

    <h1 id="question_title">{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <div style="color:#ed1c24;font-size:25px;padding-left:50px;padding-bottom:20px;font-family: Arial, Helvetica, sans-serif;"
         id="results_loader">


    </div>
    <form action="{% url 'polls:vote' question.id %}" method="post" id="post_form">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
        {% endfor %}
        <input type="submit" value="Vote" id="input_button" class="btn2"/>
    </form>
    {% block javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
             $('#logout_btn').click(function(e){
                    sessionStorage.clear();
             });

            $('#post_form').on('submit',function(e){
                e.preventDefault();
                var x = $('input[name=choice]:checked', '#post_form').val();

                {% for choice in question.choice_set.all %}
                    if ({{ choice.id }} == x){
                        var cho = "{{ choice.choice_text }}";
                    }
                {% endfor %}

                 $.ajax({
                    type:'POST',
                    url: '{% url 'polls:vote' question.id %}',
                    data:{
                        choice : x,
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                    },
                    success:function(data){
                        if (typeof(x) != "undefined"){
                            $("#post_form").hide();
                        }
                        $("#results_loader").html(data);

                            var i;
                            var str;
                            var y = parseInt(x);
                            var quests = JSON.parse( sessionStorage.getItem('quests'));
                            if (quests == undefined){
                                var quests = {};
                                quests[0] = {question : "{{ question.question_text }}", choice : cho, votes : 0};
                                str = JSON.stringify(quests);
                                sessionStorage.setItem('quests', str);
                            }

                            var bl = false;
                            for (i=0; i<Object.keys(quests).length; i++){
                                if (isNaN(y)) {
                                    break;
                                }
                                else{
                                    if ( cho == quests[i].choice){
                                        quests[i].votes++;
                                        bl = true;
                                        break;
                                    }
                                }
                            }

                            if ( bl == false && !(isNaN(y))){
                                quests[Object.keys(quests).length] = {question : "{{ question.question_text }}", choice : cho, votes : 1};
                            }
                            str =  JSON.stringify(quests);
                            sessionStorage.setItem('quests', str);

                    }
                });
            });

            $('#history_button').on('click',function(e){
                e.preventDefault();
                $.ajax({
                    url: '{% url 'polls:history' %}',
                    success:function(data){
                        $("#post_form").hide();
                        $("#question_title").hide();
                        $("#results_loader").html(data);
                        document.getElementById("results_loader").style.color = "white";
                        document.getElementById("results_loader").style.paddingTop = "50px";
                    }
                });
            });


    </script>
    {% endblock %}
</div>
</body>
</html>

polls/templates/polls/history.html
<body>
<head>
    <style>
    table{
        width:60%;
        border-style:double;
        text-align:center;
        font-size:30px;
        color:white;
        font-family: Arial, Helvetica, sans-serif;
    }

        table tr:hover{
            background:#ed1c24;
        }

    </style>
</head>
<p>Vote History</p>
<div id="sessiondata">
</div>

{% block javascript %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>

    var tb = "<table border='1'>";
    tb+="<tr><th>Question</th><th>Choice</th><th>Votes</th></tr>";
    var quests = JSON.parse( sessionStorage.getItem('quests'));

    for (i=0; i<Object.keys(quests).length; i++){
        tb += "<tr><td>" +quests[i].question + "</td><td>" +quests[i].choice + "</td><td>"+quests[i].votes +"</td></tr>";
    }
    tb+="</table>";
    $("#sessiondata").html(tb);

</script>
{% endblock %}
</body>

polls/templates/polls/index.html
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static_cache %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"/>
</head>
<html>
<body>

<div class="bg-img">
    <div style="width:100px;float:right;">
        <a href="/polls/" class="btn2" style="float:right;" id="logout_btn">Logout</a>
    </div>
    {% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
</div>
{% block javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
     $('#logout_btn').click(function(e){
            sessionStorage.clear();
     });
        </script>
    {% endblock %}
</body>
</html>

polls/templates/polls/login.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static_cache %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"/>
</head>
<body>

<div class="bg-img">
    <form class="container" id="loginform" action="./login/" method="post">
        {% csrf_token %}
        <label id="error" hidden style="color:#ed1c24"><b>Wrong Credentials!</b></label>
        <label id="registered" hidden style="color:#ed1c24"><b>Account Created!</b></label>
        <label id="exists" hidden style="color:#ed1c24"><b>Account already exists!</b></label>
        <h1>Login</h1>

        <label for="username"><b>Username</b></label>
        <input type="text" placeholder="Enter Username" name="username" id="username" required>

        <label for="pwd"><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="password" id="pwd" required>

        <button type="submit" class="btn" id="loginbutton" name="login">Login</button>

        <button type="submit" class="btn" id="registerbutton" name="register" style="margin-top:10px;">Register</button>

    </form>
</div>
{% block javascript %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
            var button_pressed;
            $('#loginform button[type=submit]').on('click', function() {
                button_pressed = $(this).attr('name');
            });


            $('#loginform').on('submit',function(e){
                console.log(button_pressed);
                var uname = document.getElementById('username').value;
                var pwd = document.getElementById('pwd').value;

                if ( button_pressed == "login" ) {
                    e.preventDefault();

                     $.ajax({
                        type:'POST',
                        url: '/polls/login/',
                        data:{
                            username : uname,
                            password : pwd,
                            csrfmiddlewaretoken: "{{ csrf_token }}",
                        },
                        success:function(data){
                            if (data == "ok"){
                                window.location.href = "./index/";
                            }
                            else{
                                 $("#registered").hide();
                                 $("#exists").hide();
                                 $("#error").show();
                            }
                        }
                    });
                 }
                 else{
                     e.preventDefault();
                     $("#error").hide();
                     $("#registered").show();
                     $('#loginform').attr('action', './register');
                     $.ajax({
                        type:'POST',
                        url: '/polls/register/',
                        data:{
                            username : uname,
                            password : pwd,
                            csrfmiddlewaretoken: "{{ csrf_token }}",
                        },
                        success:function(data){
                            if ( data == "registered" ) {
                                 $("#exists").hide();
                                 $("#error").hide();
                                 $("#registered").show();
                            }
                            else {
                                 $("#registered").hide();
                                 $("#error").hide();
                                 $("#exists").show();
                            }
                        }
                    });
                 }
            });



</script>
{% endblock %}
</body>
</html>

polls/templates/polls/results.html
<form id="resultform">
    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}" class="btn2">Vote again?</a>
</form>

polls/templates/polls/serverhistory.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static_cache %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"/>
        <style>
    table{
        margin-left:30px;
        width:60%;
        border-style:double;
        text-align:center;
        font-size:30px;
        color:white;
        font-family: Arial, Helvetica, sans-serif;
    }

    table tr:hover{
        background:#ed1c24;
    }

    p{
        color:white;
        font-size:30px;
        margin-left:30px;
        margin-top:0px;
        padding-top:30px;
    }

    </style>
</head>
<body>
<div class="bg-img">
    <div style="width:100px;float:right;">
        <a href="/polls/" class="btn2" style="float:right;" id="logout_btn">Logout</a>
        <a href="/polls/index/" class="btn2" style="float:right;">Back</a>
    </div>
    <div id="serverdata">

        <p>Server Votes History</p>

        <table border="1">
            <tr><th>Question</th><th>Choice</th><th>Votes</th></tr>
    {% for question in request.session.squests %}
            <tr><td>{{ question.Question }}</td>
                <td>{{ question.Choice }}</td>
            <td>{{ question.Votes }}</td></tr>

            {% endfor %}
     </table>

    </div>
</div>


{% block javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>

        $('#logout_btn').click(function(e){
           sessionStorage.clear();
        });
        </script>
    {% endblock %}
</body>
</html>